version: '3.8'

services:
  # master
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6400:6379"

  # replica-1
  redis-replica-1:
    image: redis:latest
    container_name: redis-replica-1
    ports:
      - "6401:6379"
    command: redis-server --replicaof redis-master 6379

  # replica-1
  redis-replica-2:
    image: redis:latest
    container_name: redis-replica-2
    ports:
      - "6402:6379"
    command: redis-server --replicaof redis-master 6379

  # sentinel setup
  sentinel-1:
    image: redis:latest
    container_name: redis-sentinel-1
    ports:
      - "26400:26379"
    volumes:
      - ./sentinel/sentinel.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master

  sentinel-2:
    image: redis:latest
    container_name: redis-sentinel-2
    ports:
      - "26401:26379"
    volumes:
      - ./sentinel/sentinel.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master

  sentinel-3:
    image: redis:latest
    container_name: redis-sentinel-3
    ports:
      - "26402:26379"
    volumes:
      - ./sentinel/sentinel.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master