spring:
  application:
    name: message-brokers-server
  profiles:
    active: {SPRING_PROFILES_ACTIVE:local}

server:
  error:
    whitelabel:
      enabled: false

app:
  messaging:
    use-amqp: false
    use-redis: false
    use-kafka: true