services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6400:6379"
    # AOF 영속화
    command: ["redis-server", "--appendonly", "yes"]
    # 데이터 영속화
    volumes:
      - redis_data:/data

volumes:
  redis_data: